# 📛 .github/workflows/angel-bot.yml

name: Angel One Auto Trader

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  trade-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install gspread oauth2client pandas requests pyotp

      - name: Create creds.json from secret
        run: echo "${{ secrets.GOOGLE_CREDENTIALS_JSON }}" > creds.json

      - name: Run main.py
        env:
          ANGEL_API_KEY: ${{ secrets.ANGEL_API_KEY }}
          ANGEL_API_SECRET: ${{ secrets.ANGEL_API_SECRET }}
          CLIENT_CODE: ${{ secrets.CLIENT_CODE }}
          TOTP: ${{ secrets.TOTP }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
        run: python main.py

