name: Auto Signal Bot

on:
  schedule:
    - cron: "*/15 * * * *"  # हर 15 मिनट पर चलेगा
  workflow_dispatch:        # मैन्युअल रन का ऑप्शन भी रहेगा

jobs:
  run-algo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install gspread oauth2client pyotp

      - name: Create creds.json from Secret
        run: echo "${{ secrets.GOOGLE_CREDENTIALS_JSON }}" > creds.json

      - name: Run main.py
        env:
          GOOGLE_APPLICATION_CREDENTIALS: creds.json
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
          ANGEL_API_KEY: ${{ secrets.ANGEL_API_KEY }}
          ANGEL_API_SECRET: ${{ secrets.ANGEL_API_SECRET }}
          CLIENT_CODE: ${{ secrets.CLIENT_CODE }}
          TOTP: ${{ secrets.TOTP }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py
