auto-signal-bot.yml

name: Auto Signal Bot

on:
  schedule:
    - cron: "*/15 * * * *"  # à¤¹à¤° 15 à¤®à¤¿à¤¨à¤Ÿ à¤ªà¤° à¤‘à¤Ÿà¥‹ à¤°à¤¨
  workflow_dispatch:        # à¤®à¥ˆà¤¨à¥à¤¯à¥à¤…à¤² à¤°à¤¨ à¤•à¥€ à¤¸à¥à¤µà¤¿à¤§à¤¾

jobs:
  run-algo:
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ“¥ Checkout Repository
        uses: actions/checkout@v4

      - name: ðŸ Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: ðŸ“¦ Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install gspread oauth2client pyotp

      - name: ðŸ“„ Create Google Credentials File
        run: echo '${{ secrets.GOOGLE_CREDENTIALS_JSON }}' > creds.json

      - name: ðŸš€ Run main.py
        env:
          GOOGLE_APPLICATION_CREDENTIALS: creds.json
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
          ANGEL_API_KEY: ${{ secrets.ANGEL_API_KEY }}
          ANGEL_API_SECRET: ${{ secrets.ANGEL_API_SECRET }}
          CLIENT_CODE: ${{ secrets.CLIENT_CODE }}
          TOTP: ${{ secrets.TOTP }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py

