name: Run Algo Trading Bot - FINNIFTY

on:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.10
          environment-name: algoenv
          activate-environment: true

      - name: Install Python Dependencies
        shell: bash -l {0}
        run: |
          conda install pip -y
          pip install -r requirements.txt
          pip install flake8 pytest

      - name: Lint with flake8
        shell: bash -l {0}
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with pytest
        shell: bash -l {0}
        run: |
          pytest || echo "No tests found, skipping..."

      - name: Create credentials.json from secret
        shell: bash -l {0}
        run: echo "${{ secrets.GOOGLE_SHEET_CREDS_JSON }}" > credentials.json

      - name: Run Algo Bot (main.py)
        shell: bash -l {0}
        env:
          ANGEL_API_KEY: ${{ secrets.ANGEL_API_KEY }}
          ANGEL_API_SECRET: ${{ secrets.ANGEL_API_SECRET }}
          CLIENT_CODE: ${{ secrets.CLIENT_CODE }}
          TOTP: ${{ secrets.TOTP }}
          SHEET_ID: ${{ secrets.SHEET_ID_FINNIFTY }}
        run: python main.py
